# Generated by Django 2.2.4 on 2020-01-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('dress_id', models.AutoField(primary_key=True, serialize=False)),
                ('dress_name', models.CharField(default='bridal dress', max_length=50)),
                ('category', models.CharField(default='', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=3000)),
                ('colours', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('material', models.CharField(max_length=100)),
                ('stitching', models.CharField(max_length=19)),
                ('contact', models.CharField(max_length=12)),
                ('image', models.ImageField(default='', upload_to='shoppage/images')),
            ],
        ),
        migrations.CreateModel(
            name='Quickform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_name', models.CharField(max_length=15)),
                ('dress_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(default='pakistan', max_length=10)),
                ('zipcode', models.IntegerField(default=0)),
            ],
        ),
    ]
