# Generated by Django 2.2.4 on 2020-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppage', '0002_auto_20200103_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=8)),
            ],
        ),
    ]
