# Generated by Django 2.2.4 on 2020-01-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppage', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='vendor_name',
            field=models.CharField(default='Khadis', max_length=50),
        ),
    ]
